# Game item dictionaries
itemNames = (
    'short sword',
    'dagger',
    'padded armor',
    'leather armor',
    'studded armor',
    'scalemail',
    'chainmail',
    'banded armor',
    'splintmail',
    'plate armor',
    'thaumaturge robes',
    'pointed hat',
    'small shield',
    'medium shield',
    'large shield',
    'spell book',
    'lock picking kit',
    'rope',
    'healing potion',
    'water',
    'dusty bread',
    'fresh bread',
    'muffin',
    'cake',
    'small toy',
    'chefs hat',
    'mana potion',
    'silken thread',
    'sharp teeth',
    'moldy cheese',
    'blood orange'
)

itemDescriptions = {
    'short sword':['A sword about one third the length of your body. It feels comfortable',
                   'in your hand.',
'        ▄▄',
'       (▓█)',
'        │║',
'        │║',
'    ╬┬┬┬╣╠┬╦╦╬',
'    ╬╩╩┼╩╩┼╩╩╬',
'       │▒░╣',
'       │▒░╣',
'       │▒░╣',
'       │▒░╣',
'       │▒░╣',
'       │▒░╣',
'       │▒░╣',
'       │▒░╣',
'       │▒░╣',
'       │▒░╣',
'       │▒░╣',
'       │▒░╣',
'       \▒░/',
'        \/'
    ],
    'dagger':       ['A sharp dagger that gleams in the light when you hold it up. It\'s ',
                     'not much, but still looks dangerous.',
'        (o)    ',
'       («0»)   ',
'        ├x╣    ',
'        ├x╣    ',
'    /═══┼X╬═══\ ',
'    \╩╩╩┼═┼╩╩╩/ ',
'        ╠░║    ',
'        ╠░║    ',
'        ╠░║    ',
'        ╠░║    ',
'        ╠░║    ',
'        ╠░║    ',  
'        ╠░║    ',
'        \░/    ',
'         V     '
    ],
    'padded armor': ['Light weight, fabric armour that fits you comfortably, although is',
                     'getting a little warm for your tastes.',
'            _______      _______',
'           /▒▒░░░░░\____/░░░░▒▒▓\\',
'          /▒░░░░░░░░░▒▒▓▓▒░░░░▒▒▓\\',
'         /▒░░░▒▒▒▒▒░░░░░░░░░░░░▒▓▒\\',
'        /▒░░▒▒▓▒▒▒░░░░░░░░░▒░░░▒▒▓▒\\',
'       /▒░░░▒▓┼▒▒░░░░░░░░░░░▒▓┼▓▒▒▓▒\\',
'      /▒░░░▒▓▓└▒░░░░░░░░░░░▒▒▓▓▓▒▒▓▓▒\\',
'     |▒░░░▒▒▓▓▓\▒░░░░░░░░░░░▒▓▓▓░▒▓▓▓▒\\',
'      \▒░░░▒▓▓▓▓▓\▒░░░░░░░░▒▒▒▓▓░░▒▓▓▓▒\\',
'        \▒▒░▒▓▓▓▓▓▓┐▒▒░░░░░▒▒▒▓\░▒▒▒▒▓▓▒\\',
'          \▒░▒▒▒▓▓▓▓▒▒▒░░░░▒▒▒▓│\░░▒▒▒▓▓▒\\',
'            \▒░▒▓▓/▒▒▒▒▒░░░▒▒▒▓│ \░░▒▒▒▓▓▒\\',
'             │\▓/▒▒▒▒▒▒▒░░▒▒▒▒▓│  \░░▒▒▒▒▓▒\\',
'             │░▒▒░░▒▒▒▒▒░░░▒▒▒▓│   \░░▒▒▒▒▓▒/',
'             │░▒▒▒░░░░░░░░▒▒▒▒▓│',
'             │░▒▒▒░░░░░░░░░▒▒▒▓│',
'             └░▒▒▒░░░░░░░░░▒▒▒▓┘'
                     ],
    'leather armor':['Light, sturdy armor. When you smell it, it reminds you of nature.'
'            _______      _______',
'            ┼░░░  ▒\____/    ▒▒╬,'
'            ┼▒░░░  ▒    ░░  ▒▒▒╬',
'             ┐▒░░░░   |░░░   ▒╓',
'             |▒▒░░░░ ▒╟░░░░  ▒║',
'             |▒░░░__  ╟░░░___▒║',
'             \▒▒░░░    ▒░░  ▒▒/',
'              |▒▒░░──┘ └── ▒▒▒║',
'              |▒░░───┐▒┌─── ▒▒║',
'              \▒▒░ ──┘▒└── ▒▒▒/',
'              \▒░░░───╬────  ▒/',
'              /░░░░░░░    ▒▒▒▒\\',
'             /╦┬┬┬┬╦┬┬╦╦╦┬╦╦╦╦┬\\',
'             ───═───══─═══─═─══─',
                     ],
    'studded armor':['Medium weight armor. It\'s made of stiff leather and brass studs.'],
    'scalemail':    ['Heavy weight armor. Picking it up is difficult, but the overlapping steel',
                     'scales look like they could protect you from most anything.'],
    'chainmail':    ['Heavy armor that jingles with every little movement. There\'s no way you',
                     'could sneak in this, but you\'re pretty sure it\'ll defend you.'],
    'banded armor': ['The definition of articulation. This heavy armor is the most moveable',
                     'of all the metal armors you\'ve encountered.'],
    'splintmail':   ['Heavy armor that you\'re pretty sure took years to make.'],
    'plate armor':  ['Heavy, study armor. You could face anything in this armor, even if it',
                     'does look battered.'],
    'thaumaturge robes': ['A warm, woolen tunic that looks no more thaumaturgely than hamster in a wheel.',
                     'It\'s seen a lot of use, however, so the wool is soft and comforting on',
                     'your skin.'],
    'pointed hat':  ['This hat looks majestic and magical. The fabric may be frayed, the copper',
                     'stars and moons tarnished, but it has an aura about it that almost glows.'],
    'small shield': ['A small shield with a metal handle on the back. It looks like it will',
                     'only give you a little protection.',
'                ┼┼┼┼╬╬╬╬',
'              ┼┼OOOØØØØØ╬',
'             ┼OO┼░░░▒▒▓╬ØØ╬',
'           ┼OO┼░▒░┌──┐░▒▓╬ØØ╬',
'          ┼OO┼░░░┌┘▒▓└┐▒▓▓╬ØØ╬',
'          ┼OO┼░▒┌┘░▒▓█└┐▒▓╬ØØ╬',
'          ┼OO┼░░└─┐▒▓┌─┘▓▓╬ØØ╬',
'           ┼OO┼░░▒│▒▓│▒░▓╬ØØ╬',
'             ┼OO┼░└──┘▒▒╬ØØ╬',
'               ┼OO┼┼╬╬ØØØ╬',
'                ┼┼OOØØ╬',
'                  ┼OØ╬'
                     ],
    'medium shield':['A medium-sized shield with an arm strap and a handle. This shield is',
                     'small enough to be travel-friendly, but large enough to offer you a',
                     'lot of protection.',
'          ┼┼┼┼┼╬╬╬╬╬╬╬',
'         ┼OOOOOOØØØØØØ╬',
'        ┼O░░░▒░░▒░▒▒▓▓Ø╬',
'       ┼O░░░░▒┌──┐░░▒▓▒Ø╬',
'      ┼O░░▒┌──┤▒▓├────┐▒Ø╬',
'     ┼O░░┌─┘┌─┤░▒├───┐│▓▒Ø╬',
'    ┼O░░▒│  │░│░▓│▒░▒└┘▒▓▓Ø╬',
'     ┼O░┌┘ ┌┘▒│░▒│░▒▓▓▒▓▓Ø╬',
'      ┼O│  └──┴──┴──┐▒▓▓Ø╬,',
'       ┼└─────┬──┬─┐│▓░Ø╬',
'        ┼O░▒┌─┤▒▓├─┘│▒Ø╬',
'         ┼O░│ ┴─┐├──┘Ø╬',
'          ┼O└─┬┐││▓▓Ø╬',
'           ┼O▒└┤├┘▒Ø╬',
'            ┼O░└┘▓Ø╬',
'             ┼O░▒Ø╬',
'              ┼OØ╬',
'               ┼╬'
                     ],
    'large shield': ['A great, heacy shield, made to stand up to horse and orc stampedes.',
                     'You\'re pretty sure this could even stop a dragon. That is, if you\'re', 
                     'strong enough to hold up a whole dragon.',
'    ╔╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╤╗',
'    ╟┼┼┼┼┼┼┼┼┼┼┼╬╬╬╬╬╬╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼┼┼┼┼┼╬╬╬╬╬╬╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼┼┼┼┌───┐╬╬╬╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼┼┼┼│░▒▓│╬╬╬╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼┌─┐└┐░┌┘┌─┐╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼└┐└┐│▒│┌┘┌┘╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼ └┐└┤┌┴┘┌┘╬╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼┼┼└─┼┘┌─┤╬╬╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼┼┼┌─┘┌┼ └┐╬╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼┤┌┘░┌┘│░▒│╬╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼┼└┐░┤┌┴▒┌┘╬╬╬╬╬╬╬╣',
'    ╟┼┼┼┼┼┼┼┼└─┼┘┌─┤╬╬╬╬╬╬╬╣',
'     ╟┼┼┼┼┼┼┼┤┌┘┌┼┐└┐╬╬╬╬╬╬╣',
'      ╟┼┼┼┼┼┼┌┘┌┘│└┐└┐╬╬╬╬╣   ',                  
'       ╟┼┼┼┼┌┘┌┤▓│╬└┐└┐╬╬╣',
'        ╟┼┼┼└─┘│▒│╬╬└─┘╬╣',
'         ╟┼┼┼┼┼└─┘╬╬╬╬╬╣',
'          ╟┼┼┼┼┼╬╬╬╬╬╬╣',
'           ╟┼┼┼┼╬╬╬╬╬╣',
'            ╟┼┼┼╬╬╬╬╣',
'             ╙╨╨╩╩╩╝   '    
                     ],
    'spell book':   ['This is a dank and mouldy tome, handed down from generation to',
                     'generation. The pages look worn, the edges are frayed and torn. In ',
                     'some places, it even looks like pages were torn out.'],
    'lock picking kit':['While far from being the best crafted, these lock picks are sturdy',
                        'and useful. You can tell that many skillful hands have manipulated',
                        'these tools.'],
    'rope':         ['This rope is strong and thick. It would take a dragon biting through this',
                     'rope to cut it.'''],
    'healing potion':['A small glass vial, filled with a shimmering silver liquid. This',
                      'potion looks like it\'s brimming over with magic. There\'s not very much,',
                      'but it looks like enough to keep you going for a while.',
'              O       ',
'          o           ',
'                O     ',
'          ________    ',
'         (     o  )   ',
'          \      /    ',
'          │  O   │    ',
'          │      │    ',
'         /        \   ',
'       ( o    O     ) ',
'     (░ █▓░░ ░  o░▓  ░)',
'    (▓▓██▒▒▒░▒▒▒░▒░░▓░░)',
'    (▓█▓▓▓██▓▓▒▒░▓░▒░░▒)',
'    (▓▓██▓▓▓▒▒▓▓▓▒░░░▒▒)',
'     \▓▓██▓▓▓█▒▓▒░░░░▒/',
'      \▓▓██▓▓██▓▒░░▒▒/',
'       \▀▀▀▀▀▀▀▀▀▀▀▀/'
    ],
    'water':['This water is clear and clean. It would be perfect to quench your thirst.'],
    'dusty bread':['The dust caked on top of this bread is kind of disturbing, but it\'s probably',
                   'safe to eat.'],
    'fresh bread':['The aroma of the fresh bread fills your nostils and makes your mouth water.'],
    'muffin':['The muffin is dense and delicious looking.  They smell sweet and rich with flavor.'],
    'cake':['Delicately glazed with light, fluffy cake sitting here makes your mouth water.'],
    'small toy':['A well-loved little toy, with the paint almost all rubbed off.'],
    'chefs hat':['A tall, white hat, almost as majestic as a thaumaturges hat. It smells like flour.'],
    'mana potion':['A purple, glowing liquid resides in this container. You feel refreshed just looking',
                   'at it.',
'              O       ',
'          o           ',
'                O     ',
'       _______________    ',
'      (            o  )   ',
'       \     o       /    ',
'       /             \\',
'      (   O           )    ',
'     (░ █▓░░ ▒ ░▒▒o░▓░ )   ',
'    (░▓███▓▓▓▒▒▓▓▓▒▒▓▒░░) ',
'   (░▓▓██▓▓██▓▓░░▒▓▓▓▓▒▓░)',
'   (▒▓██████▓▓▓▒▓▓▓▒▒░░░▒) ',
'   (▒██████▓██▓▓▓▓▒▒▒▒░▓▒)',
'   (▒█▓████▓▓▓█▓▓▒▓▒▒░░▓▒)',
'    (█▓▓▓████▓▓█▓▓▓▓▓░▒▒)',
'     \█▓▓█████▓█▓█▓▓▓░▒/',
'      \██▓█████▓█▓█▒▒▓/',
'       \▀▀▀▀▀▀▀▀▀▀▀▀▀/'],
    'silken thread':['A sticky, but strong thread that looks like it could be used as rope.'],
    'sharp teeth':['These teeth are from some sort of animal. You have to be careful when handling',
                   'them, for fear of cutting yourself.'],
    'moldy cheese':['This cheese absolutely reeks. You could probably eat it, but it might make you sick.'],
    'blood orange':['Peeling open this orange reveals blood red flesh and juice. It smells delicious.']
}

itemType = {
    'short sword':      'weapon',
    'dagger':           'weapon',
    'padded armor':     'armor',
    'leather armor':    'armor',
    'studded armor':    'armor',
    'scalemail':        'armor',
    'chainmail':        'armor',
    'banded armor':     'armor',
    'splintmail':       'armor',
    'plate armor':      'armor',
    'thaumaturge robes':'clothes',
    'pointed hat':      'hat',
    'small shield':     'shield',
    'medium shield':    'shield',
    'large shield':     'shield',
    'spell book':       'book',
    'lock picking kit': 'unlock',
    'rope':             'climb',
    'healing potion':   'potion',
    'water':            'potion',
    'dusty bread':      'food',
    'fresh bread':      'food',
    'muffin':           'food',
    'cake':             'food',
    'small toy':        'item',
    'chefs hat':        'hat',
    'mana potion':      'potion',
    'silken thread':    'item',
    'sharp teeth':      'item',
    'moldy cheese':     'food',
    'blood orange':     'food'    
}

wieldTypes = (      #Wieldable items
    'weapon',
    'shield',
    'wand'
)

wearTypes = (       #Wearable items
    'clothes',
    'hat',
    'armor'
)

useTypes = (        #Usable items
    'tool',
    'potion',
    'book',
    'spell',
    'climb',
    'unlock',
    'food'
)

craftTypes = (
    'item',
    'material' #?
)

weaponHitDice = {   #Number of dice and number of sides on dice
    'short sword':  '1 6',
    'dagger':       '1 4'
}

weaponStat = {
    'short sword':  'strength',
    'dagger':       'dexterity'
}

armorClass = {
    'padded armor': '1',
    'leather armor':'2',
    'studded armor':'3',
    'scalemail':    '4',
    'chainmail':    '5',
    'banded armor': '6',
    'splintmail':   '7',
    'plate armor':  '8',
    'small shield': '1',
    'medium shield':'2',
    'large shield': '3'
}

wearables = {
    'padded armor':     'armor',
    'leather armor':    'armor',
    'studded armor':    'armor',
    'scalemail':        'armor',
    'chainmail':        'armor',
    'banded armor':     'armor',
    'splintmail':       'armor',
    'plate armor':      'armor',
    'thaumaturge robes':'clothes',
    'pointed hat':      'hat',
    'small shield':     'shield',
    'medium shield':    'shield',
    'large shield':     'shield',
    'chefs hat':        'hat'
}

itemPrices = {
    'short sword':10,
    'dagger':2,
    'padded armor':4,
    'leather armor':5,
    'studded armor':20,
    'scalemail':120,
    'chainmail':75,
    'banded armor':200,
    'splintmail':80,
    'plate armor':600,
    'thaumaturge robes':1,
    'pointed hat':1,
    'small shield':3,
    'medium shield':7,
    'large shield':10,
    'spell book':50,
    'lock picking kit':30,
    'rope':1,
    'healing potion':20,
    'water':1,
    'dusty bread':1,
    'fresh bread':7,
    'muffin':10,
    'cake':22,
    'small toy':10,
    'chefs hat':6,
    'mana potion':22,
    'silken thread':9,
    'sharp teeth':3,
    'moldy cheese':5,
    'blood orange':15
}

consumableInfo = {
    # stat, max effect
    'healing potion':['health', 6],
    'water':['magic', 1],
    'dusty bread':['health', 3],
    'fresh bread':['health', 5],
    'muffin':['health', 3],
    'cake':['health', 7],
    'mana potion':['magic',6],
    'moldy cheese':['health',-5],
    'blood orange':['magic', 10]
}

minReqs = {
    # str, int, dex
    'short sword':[6, 1, 4],
    'dagger':[4, 1, 4],
    'padded armor':[4, 1, 1],
    'leather armor':[6, 1, 2],
    'studded armor':[8, 1, 4],
    'scalemail':[10, 1, 6],
    'chainmail':[12, 1, 8],
    'banded armor':[14, 1, 10],
    'splintmail':[16, 1, 12],
    'plate armor':[18, 1, 14],
    'small shield':[2, 1, 1],
    'medium shield':[6, 1, 2],
    'large shield':[10, 1, 4],
    'spell book':[1, 8, 1],
    'lock picking kit':[1, 4, 8],
    'rope':[8, 1, 6],
}




