import time

print("Guide to playing The Dojo")
time.sleep(1)

print("\n\nWalking")
print("------------------")
print("go")
print("move")
print("run")
print("walk")
print("leave")

print("\n(n) North")
print("(e) East")
print("(w) West")
print("(s) South")
print("(example: walk w)")


print("\n\nLooking          #Note: use full names")
print("------------------")
print("look 	            #you look around you")
print("look at (item, monster, NPC)")
print("Example: look at skeleton")
print("look at inventory    #Check your inventory")


print("\n\nGetting Items")
print("-------------------")
print("get")
print("grab")
print("take")
print("Example: grab short sword")

print("Press enter to continue...")
input()

print("\n\nDropping Items")
print("-------------------")
print("drop")
print("throw")
print("leave")
print("Example: throw healing potion")

print("\n\nEquipping Items")
print("-------------------")
print("equip")
print("hold")
print("wield")
print("wear")
print("Example: wear wizard robes")

print("\n\nUnequipping Items")
print("-------------------")
print("unequip")
print("remove")
print("Example: unequip pointed hat")

print("\nSaving and Quiting")
print("-------------------")
print("save")
print("quit")

print("Press enter to continue...")
input()

print("\nAttacking Enemies")
print("-------------------")
print("attack")
print("hit")
print("kill")
print("kick")
print("punch")
print("There are many other commands. Experiment!")
print("Example: kill goblin")

print("\nLooting Enemies")
print("-------------------")
print("loot")
print("plunder")
print("maraud")
print("pillage")
print("Example: loot fairy")

print("\nUsing an Item")
print("-------------------")
print("use")
print("Example: use healing potion")
print("Action under development.")

print("\nTalking")
print("-------------------")
print("talk")
print("speak")
print("Example: talk to guard")
print("Action under development.")

print("End of Help. Press enter to continue...")
input()
